### ISSUE TITLE
Loose option case

### ISSUE THREAD

**Issue by mistic100** [tandrewnichols/opted#2]
Hello,

I have a problem with simple-cli where I cannot use the "X" option of git merge because of the use of _.kebabCase here https://github.com/tandrewnichols/opted/blob/master/lib/opted.js#L11

It converts "X" to "x" thus not recognised by git. Of course I will use the long option "strategy-option" but I think the module should not change the case, at least for one letter options

**Comment by tandrewnichols** [comment]
Yep, totally right. Thanks! I'll work on it this week.

**Comment by tandrewnichols** [comment]
I just published opted@1.0.2 to address this. I will, however, still need to update this dependency in simple-cli and grunt-simple-git (et al.)

**Comment by tandrewnichols** [comment]
Actually . . . I always forget this, but as it's a patch, reinstalling those _should_ just pick this version up.
